GET http://localhost:3001/products

###
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Another Test",
  "description": "Second generic product name",
  "quantity": 5
}

###
DELETE http://localhost:3001/products/1