GET http://localhost:3001

###
GET http://localhost:3001/products

###
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "",
  "description": "",
  "quantity": "rtert"
}

###
DELETE http://localhost:3001/products/4