GET http://localhost:3001

###
GET http://localhost:3001/products

###
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Testing Product",
  "description": "Generic description",
  "quantity": 80
}

###
DELETE http://localhost:3001/products/nQqpCZGubcO8geF6c9LP4