### Default Page
GET http://localhost:3001

### HEAD
HEAD http://localhost:3001/products

### Product list
GET http://localhost:3001/products

### Single product
GET http://localhost:3001/products/604b05f9df68fe39b05d3b92

### Invalid product
GET http://localhost:3001/products/6048daa298f9cc04f4e778f6

### Adding product
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "qreqte",
  "description": "qttqtrq",
  "quantity": 55
}

### Removing product
DELETE http://localhost:3001/products/5a3d5da59070081a82a3445