GET http://localhost:3001

### Product list
GET http://localhost:3001/products

### Single product
GET http://localhost:3001/products/w11H5lBZ2UPC5P6Hi9RzT

### Invalid product
GET http://localhost:3001/products/qewtq

### Adding product
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Testing Product",
  "description": "Generic product description",
  "quantity": 99
}

### Removing product
DELETE http://localhost:3001/products/WsY9WlafbRlDc7gGYD3_w